name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip the application for deployment
      run: zip -r application.zip * .[^.]*

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Replace with your AWS region
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}

      run: |
        pip install awsebcli
        eb init -p python-3.11 ML-ebs --region $AWS_REGION --platform python-3.11
        # Set the default environment
        eb use $EB_ENV_NAME
        eb deploy $EB_ENV_NAME
